arch:
  - amd64
  - arm64

os: linux
language: rust

addons:
  apt:
    update: true

rust:
  - stable
  - 1.56.1

before_install:
  - sudo apt-get -y install libfontconfig1-dev jq
  - rustup component add clippy

script:
  - cargo clippy

  - cargo test
  - |
    if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
      ./ci/ldd-grep
    else
      true
    fi

  # Rust 1.46.0 cargo doesn't accept carget test --features
  - cargo test --features dlopen --manifest-path fontconfig/Cargo.toml
  - |
    if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
      ./ci/ldd-grep -v -- --features dlopen
    else
      true
    fi

  - RUST_FONTCONFIG_DLOPEN=on cargo test
  - |
    if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
      RUST_FONTCONFIG_DLOPEN=on ./ci/ldd-grep -v
    else
      true
    fi

  - diff -u <(fc-list) <(cargo run --example fc-list)

  - |
    diff -u \
    <(fc-list --verbose monospace) \
    <(cargo run --example fc-list -- --verbose monospace)

  # fc-list with file and lang property
  - |
    diff -u \
    <(fc-list monospace file lang) \
    <(cargo run --example fc-list -- monospace file lang)

  # fc-pattern with ConfigSubstitute and DefaultSubstitute
  - |
    diff -u \
    <(fc-pattern -d -c monospace) \
    <(cargo run --example fc-pattern -- -d -c monospace)

  - |
    diff -u \
    <(fc-pattern monospace) \
    <(cargo run --example fc-pattern -- monospace)
